# Generated by Django 5.2 on 2025-05-12 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_vendor_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_staff_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorstaff',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_vendor', to='users.vendor'),
        ),
    ]
