# Generated by Django 5.2 on 2025-07-21 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_vendorstaff_user_alter_vendorstaff_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(default=datetime.datetime(2025, 7, 25, 5, 5, 44, 609980, tzinfo=datetime.timezone.utc), max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
