# Generated by Django 5.2 on 2025-05-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subscription_invoice_usagelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planfeature',
            old_name='trial_quata',
            new_name='trial_quota',
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
