# Generated by Django 5.2 on 2025-05-12 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_trial_quata_planfeature_trial_quota_and_more'),
        ('users', '0003_customer_vendor_alter_customer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planfeature',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='planfeature',
            name='trial_quota',
        ),
        migrations.RemoveField(
            model_name='planfeature',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='usagelog',
            name='feature',
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_quota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default='month'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_subcription', to='users.customer'),
        ),
    ]
